language: python
python:
  - 2.7
  - 3.4
  - 3.5
before_install:
  - pip install coveralls
install:
  - pip install -e .
  - pip install -r requirements.txt
script: make test
after_success:
  - coveralls
